services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - simon
    depends_on:
      - app1 
      - app2

  app1:
    build: .
    container_name: app1
    networks:
      - simon

  app2:
    build: .
    container_name: app2
    networks:
      - simon

networks:
  simon:
    driver: bridge
